import React from "react";
import { useRouter } from "next/router";
import Hero from "../../comps/Hero";
import ImgSrc from "../../public/recroom-hero.jpg";
import Image from "next/image";
import Head from "next/head";

import src from "../../public/hero-home.jpg";

export async function getServerSideProps({ params }) {
  try {
    const data = await fetch(
      `https://generdate-api.herokuapp.com/activities/${params.id}`
    );
    const activity = await data.json();

    return {
      props: {
        activity,
      },
    };
  } catch (error) {
    // Handle the error by returning an error page or a fallback component
    return {
      props: {
        error: {
          message: "Failed to fetch activity data",
        },
      },
    };
  }
}

export default function ActivityPage({ activity }) {
  const router = useRouter();
  const mapSrc = `https://maps.google.com/maps?&q="+${activity.address}"&output=embed`;

  if (router.isFallback) {
    return <div>Loading...</div>;
  }

  console.log(activity);

  return (
    <>
      {/* <div> */}
      <Head>
        <title>{activity.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@200;400;500&family=Russo+One&display=swap"
          rel="stylesheet"
        />
      </Head>

      {/* NEW HERO */}
      <div class="flex justify-center items-center relative w-full h-96 p-20">
        <div class="absolute object-cover w-full h-full">
          <img
            src={activity.feature}
            style={{ width: "100%", height: "100%", objectFit: "cover" }}
          />
        </div>

        <div class="relative flex flex-col items-center">
          <h1 class="text-red-500 text-1xl font-roboto-mono font-extralight"></h1>
          <p class="text-red-500 text-5xl font-medium font-roboto-mono"></p>
        </div>
      </div>
      {/* NEW HERO */}

      {/* <Hero img={ImgSrc} /> */}

      <div className="flex justify-center w-full">
        <div className="flex flex-col md:flex-row w-3/4 p-5">
          {/* 2 columns of activity data */}
          <div className="flex flex-grow flex-col p-4 px-2 md:order-1 md:px-24">
            <h1 className="text-3xl font-bold font-roboto-mono">
              {activity.name}
            </h1>
            <p className="font-roboto-mono text-md leading-8 mt-2">
              {activity.about}
            </p>
            <h2 className="font-roboto-mono font-bold text-2xl leading-7 mt-10">
              Why go here?
            </h2>
            <p className="font-roboto-mono text-md leading-7 mt-2">
              {activity.notes}
            </p>
          </div>

          <div className="flex flex-col md:order-2">
            <div className="flex flex-col p-10 bg-gray-300 mb-5">
              <div className="my-2">
                <h3 className="font-bold">Activity Type:</h3>
                {activity.tags.map((tag) => {
                  return <p>{tag}</p>;
                })}
              </div>

              <div className="my-2">
                <h3 className="font-bold">Best time to visit:</h3>
                <p>{activity.bestTime}</p>
              </div>

              <div className="my-2">
                <h3 className="font-bold">City:</h3>
                <p>{activity.location}</p>
              </div>

              <div className="my-2">
                <h3 className="font-bold">Address:</h3>
                <p>{activity.address}</p>
              </div>
            </div>

            <iframe
              width="300"
              height="300"
              frameborder="0"
              scrolling="no"
              marginheight="0"
              marginwidth="0"
              src={mapSrc}
            ></iframe>

            <a
              target="_blank"
              className="w-full bg-gray-400 py-3 mt-5 flex justify-center"
              href={activity.mapsLink}
              rel="noopener noreferrer"
            >
              <p>Check in Google Maps</p>
            </a>
          </div>
        </div>
      </div>
    </>
  );
}

