import React from "react";
import Head from "next/head";
import Image from "next/image";
import ArticleCard from "../../comps/ArticleCard";
import FeatureArticleCard from "../../comps/FeatureArticleCard";
import heroImg from "../../public/article-hero.jpg";
import Hero from "../../comps/Hero";

const Article = () => {
  return (
    <div className="bg-red-white">
      <Head>
        <title>Articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@200;400;500&family=Russo+One&display=swap"
          rel="stylesheet"
        />
      </Head>

      {/* <Hero image={heroImg} /> */}

      <div className="px-4 md:px-12">
        <FeatureArticleCard />

        <hr className="my-4 border-t-2 border-gray-300" />

        <h2 className="text-2xl font-bold font-roboto-mono mb-4">
          Latest articles
        </h2>

        <div className="flex flew-row flex-wrap">
          <ArticleCard />
          <ArticleCard />
          <ArticleCard />
          <ArticleCard />
          <ArticleCard />
          <ArticleCard />
        </div>
      </div>
    </div>
  );
};

export default Article;
