import React from "react";
import Hero from "../../comps/Hero";
import heroImg from "../../public/summer-hero.jpg";
import Head from "next/head";
import Image from "next/image";
import author from "../../public/author.jpg";
import ActivityImg from "../../public/PNE.jpg";

import ArticleActivityCard from "../../comps/ArticleActivityCard";

const SummerActivities = () => {
  return (
    <div class="flex items-center flex-col bg-red-white">
      <Head>
        <title>Summer Date Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@200;400;500&family=Russo+One&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Hero img={heroImg} />

      <div class="flex flex-col w-3/4 mt-10 sm:my-0 lg:w-2/4">
        <h2 class="font-archivo font-semibold text-4xl my-5">
          Summer Date Ideas
        </h2>
        <hr class="h-px my-2 bg-gray-200 border-0 dark:bg-gray-700"></hr>

        <a href="https://google.com">
          <div class="flex flex-row py-2 items-center">
            <div class="flex items-center p-2 rounded-full">
              <Image
                src={author}
                width={50}
                height={50}
                alt="author image"
                className="rounded-full"
              />
            </div>
            <div>
              <h2 class="font-archivo font-bold p-0 text-md">Raha</h2>
              <p>The creator</p>
            </div>
          </div>
        </a>

        <p class="font-archivo text-lg leading-7">
          Summer in Vancouver is a magical time when the city comes alive with
          an array of activities and events. It's the perfect season to plan a
          romantic date with your significant other or to impress a potential
          love interest. With endless possibilities, choosing the right summer
          date idea can be a challenge. That's why we've compiled a list of the
          most enchanting and exciting summer date ideas in Vancouver. From
          beach picnics to outdoor concerts, this guide has got you covered with
          ideas that will impress your partner and make your summer in Vancouver
          unforgettable. So, get ready to soak up the sun and experience the
          best of what Vancouver has to offer with these summer date ideas!
        </p>

        <ArticleActivityCard
          title={"Spanish Banks Beach"}
          link={
            "https://www.google.com/maps/place/Spanish+Banks+Beach/@49.276889,-123.2223358,16z/data=!3m1!4b1!4m6!3m5!1s0x5486728d6fbc105d:0x6de6f0c9aa88282d!8m2!3d49.2764679!4d-123.2132618!16zL20vMGRtcjYz?coh=164777&entry=tt&shorturl=1"
          }
          img={
            "https://i0.wp.com/vancouversbestplaces.com/wp-content/uploads/2018/06/Volleyball-at-Spanish-Banks.jpg?resize=640%2C300&ssl=1"
          }
          content={
            "Spanish Banks Beach is a beautiful, sandy beach located in Vancouver, British Columbia, Canada. The beach is known for its stunning views of the North Shore mountains and the city skyline, as well as its calm waters and scenic walking trails. Visitors can enjoy a range of activities at Spanish Banks Beach, including swimming, kayaking, picnicking, and beachcombing. You should visit Spanish Banks Beach for its stunning views of the North Shore mountains and the city skyline, as well as its calm waters and sandy shores. It's a great spot to relax, take a walk, have a picnic, or engage in various water activities."
          }
        />

        <ArticleActivityCard
          title={"English Bay Beach"}
          link={
            "https://goo.gl/maps/Nan1wc4PoueXbW2j9"
          }
          img={
            "https://i0.wp.com/vancouversbestplaces.com/wp-content/uploads/2018/06/Stanley-Park-Seawall-at-English-Bay.jpg?fit=640%2C280&ssl=1"
          }
          content={
            "English Bay Beach is a popular beach in Vancouver, British Columbia, Canada, located along the city's seawall. The beach is known for its stunning sunsets, sandy shores, and clear, refreshing waters. Visitors can enjoy a range of activities at English Bay Beach, including swimming, sunbathing, playing beach volleyball, and people-watching. You should visit English Bay Beach for its beautiful sunsets, sandy shores, and clear waters. It's a great place to relax, soak up the sun, and engage in various beach activities."
          }
        />

        <ArticleActivityCard
          title={"Sea to Sky Gondola"}
          link={
            "https://goo.gl/maps/Eo5kpykNNXLeNk2e6"
          }
          img={
            "https://www.vancouverplanner.com/wp-content/uploads/2019/04/sea-to-sky-lookout.jpg"
          }
          content={
            "The Sea-to-Sky Corridor, often referred to as the Corridor or the Sea to Sky Country, is a region in British Columbia spreading from Horseshoe Bay through Whistler to the Pemberton Valley and sometimes beyond to include Birken and D'Arcy. From Whistler on up, the region overlaps with the older and more historic Lillooet Country, of which Squamish, at the region's centre, was once the southward extension in the days when it was the rail-port terminus from the Interior, via Lillooet, and accessible from the Lower Mainland only by sea. Most of the region is in the Squamish-Lillooet Regional District, although south of Britannia Beach a small part of the region is in the Greater Vancouver Regional District. You should visit Sea to Sky Gondola in Vancouver for its breathtaking panoramic views of the coastal mountains and Howe Sound fjord, as well as for the exciting outdoor activities such as hiking, snowshoeing, and suspension bridge walking."
          }
        />
      </div>
    </div>
  );
};

export default SummerActivities;
