import React from "react";
import Hero from "../../comps/Hero";
import ImgSrc from "../../public/recroom-hero.jpg";

import Head from "next/head";
import { google } from "googleapis";

export async function getServerSideProps({ query }) {
  // auth
  const auth = await google.auth.getClient({
    scopes: ["https://www.googleapis.com/auth/spreadsheets.readonly"],
  });

  const sheets = google.sheets({ version: "v4", auth });

  // query
  const { id } = query;
  const range = `Sheet1!A${id}:G${id}`;

  const response = await sheets.spreadsheets.values.get({
    spreadsheetId: process.env.SHEET_ID,
    range,
  });

  // result

  const [activityid, name, address, tags, price, location, feature] =
    response.data.values[0];

  return {
    props: {
      activityid,
      name,
      address,
      tags,
      price,
      location,
      feature,
    },
  };
}

const ActivityPage = ({
  activityid,
  name,
  address,
  tags,
  price,
  location,
  feature,
}) => {
  // const ImgSrc = {feature}
  // console.log(feature)

  

  return (
    <>
    {/* <div> */}
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@200;400;500&family=Russo+One&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Hero img={ImgSrc} />
      <div className="flex justify-center w-full border-2 border-green-500">
        <div className="flex w-3/4 p-5 border-2 border-red-500">
          {/* 2 columns of activity data */}
          <div className="leftDiv flex flex-grow flex-col p-4 px-24 border-2 border-purple-300">
            <h1 className="text-2xl font-montserrat font-bold">{name}</h1>
            <p className="font-montserrat text-md leading-8">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur. Excepteur sint occaecat cupidatat non proident,
              sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <h2 className="font-montserrat font-bold text-2xl leading-7 mt-10">
              Subheader
            </h2>
            <p className="font-montserrat text-md leading-7">
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </p>
          </div>

          <div className="rightDiv flex flex-col">
            <div className="flex flex-col p-10 bg-gray-300 mb-5">
              <div className="my-2">
                <h3 className="font-bold">Activity Type:</h3>
                <p>{tags}t</p>
              </div>

              <div className="my-2">
                <h3 className="font-bold">City:</h3>
                <p>{location}</p>
              </div>

              <div className="my-2">
                <h3 className="font-bold">Address:</h3>
                <p>{address}</p>
              </div>
            </div>

            {/* <iframe
              src={`https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=4200%20Willingdon%20Ave+()&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed`}
              width="300"
              height="300"
              style={{ border: 0 }}
              allowfullscreen=""
              loading="lazy"
              referrerpolicy="no-referrer-when-downgrade"
            ></iframe> */}

              <iframe
                width="300"
                height="300"
                frameborder="0"
                scrolling="no"
                marginheight="0"
                marginwidth="0"
                src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=4200 Willingdon Ave+()&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"
              >
              </iframe>

            <button className="w-full bg-gray-400 py-3 mt-5">Add to list</button>
          </div>
        </div>
      </div>
      
    </>
    // </div>
  );
};

export default ActivityPage;
