import React from "react";
import { createClient } from "contentful";
import Hero from "../../comps/Hero";
import ImgSrc from "../../public/recroom-hero.jpg";
import Image from "next/image";
import Head from "next/head";
import NoResults from "../../public/noresults.gif";

import src from "../../public/hero-home.jpg";

const client = createClient({
  space: process.env.CONTENTFUL_SPACE_ID,
  accessToken: process.env.CONTENTFUL_ACCESS_KEY,
});

export const getStaticPaths = async () => {
  const res = await client.getEntries({
    content_type: "locations",
  });

  const paths = res.items.map((item) => {
    return {
      params: { slug: item.fields.slug },
    };
  });

  return {
    paths,
    fallback: true,
  };
};

export async function getStaticProps({ params }) {
  try {
    const { items } = await client.getEntries({
      content_type: "locations",
      "fields.slug": params.slug,
    });

    if(!items.length) {
      return {
        redirect: {
          destination: '/activities',
          permanent: false
        }
      }
    }

    return {
      props: { location: items[0] },
      revalidate: 1,
    };
  } catch (error) {
    console.error("Error fetching data:", error);
    return {
      props: { location: null },
      revalidate: 1,
    };
  }
}

export default function ActivityPage({ location }) {
  const mapSrc = location
    ? `https://maps.google.com/maps?&q="+${location.fields.address}"&output=embed`
    : undefined;

  if (!location) {
    return (
      <div className="w-full h-96 flex flex-col items-center justify-center">
        <Head>
          <title>No results...</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/icon.png" />
        </Head>
        <Image
          src={NoResults}
          alt="No results found"
          width={120}
          height={120}
        />
        <p className="text-xl font-bold">No results found</p>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>{location.fields.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@200;400;500&family=Russo+One&display=swap"
          rel="stylesheet"
        />
      </Head>

      {/* NEW HERO */}
      <div class="flex justify-center items-center relative w-full h-96 p-20">
        <div class="absolute object-cover w-full h-full">
          <img
            src={location.fields.featureImage.fields.file.url}
            style={{ width: "100%", height: "100%", objectFit: "cover" }}
            alt="feature image"
            loading="lazy"
          />
        </div>

        <div class="relative flex flex-col items-center">
          <h1 class="text-red-500 text-1xl font-roboto-mono font-extralight"></h1>
          <p class="text-red-500 text-5xl font-medium font-roboto-mono"></p>
        </div>
      </div>
      {/* NEW HERO */}

      <div className="flex justify-center w-full">
        <div className="flex flex-col md:flex-row w-3/4 p-5">
          {/* 2 columns of activity data */}
          <div className="flex flex-grow flex-col p-4 px-2 md:order-1 md:px-24">
            <h1 className="text-3xl font-bold font-roboto-mono">
              {location.fields.name}
            </h1>
            <p className="font-archivo text-md leading-8 mt-2">
              {location.fields.about}
            </p>
            <h2 className="font-roboto-mono font-bold text-2xl leading-7 mt-10">
              Why go here?
            </h2>
            <p className="font-archivo text-md leading-7 mt-2">
              {location.fields.notes}
            </p>
          </div>

          <div className="flex flex-col md:order-2">
            <div className="flex flex-col p-10 bg-gray-300 mb-5">
              <div className="my-2">
                <h3 className="font-bold">Activity Type:</h3>
                {location.fields.tags.map((tag, index) => {
                  return <p key={index}>{tag}</p>;
                })}
              </div>

              <div className="my-2">
                <h3 className="font-bold">Activity Price:</h3>
                <p>{location.fields.price}</p>
              </div>

              <div className="my-2">
                <h3 className="font-bold">Best time to visit:</h3>
                <p>{location.fields.timeToVisit}</p>
              </div>

              <div className="my-2">
                <h3 className="font-bold">City:</h3>
                <p>{location.fields.city}</p>
              </div>

              <div className="my-2">
                <h3 className="font-bold">Address:</h3>
                <p>{location.fields.address}</p>
              </div>
            </div>

            <iframe
              width="300"
              height="300"
              frameborder="0"
              scrolling="no"
              marginheight="0"
              marginwidth="0"
              src={mapSrc}
            ></iframe>

            <a
              target="_blank"
              className="w-full bg-gray-400 py-3 mt-5 flex justify-center"
              href={location.fields.googleMaps}
              rel="noopener noreferrer"
            >
              <p>Check in Google Maps</p>
            </a>
          </div>
        </div>
      </div>
    </>
  );
}
