import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import heroImg from "../public/hero-home.jpg";
import Hero from "../comps/Hero";
import author from "../public/author.jpg";

import gif from "../public/gif.gif";

const About = () => {
  return (
    <div class="flex items-center flex-col">
      <Head>
        <title>About project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@200;400;500&family=Russo+One&display=swap"
          rel="stylesheet"
        />
      </Head>

      {/* <Hero img={heroImg} /> */}

      <Hero
        img={heroImg}
        topText="Plan your dates easier with"
        header="GenerDate"
      />

      <div class="flex flex-col w-2/4 mt-4 sm:my-0 ">
        <h2 class="font-archivo font-semibold text-4xl mt-8">
          How I came up with this app idea?
        </h2>
        <hr class="h-px my-2 bg-gray-200 border-0 dark:bg-gray-700"></hr>

        <a href="https://google.com">
          <div class="flex flex-row py-2 items-center">
            <div class="flex items-center p-2 rounded-full">
              <Image src={author} width={50} height={50} alt="author image" className="rounded-full"/>
            </div>
            <div>
              <h2 class="font-archivo font-bold p-0 text-md">Raha</h2>
              <p>The creator</p>
            </div>
          </div>
        </a>

        <p class="font-archivo leading-7 mb-4">
          2020, I just moved to Vancouver.
        </p>

        <p class="font-archivo leading-7 mb-4">
          Each time I would move to a new city, I would always have the same
          problem - exploring and finding good spots for dates (especially first
          dates). It would usually take me around 3 months to find cool spots
          around the city where I would potentially go out on a date with
          someone.
        </p>

        <p class="font-archivo leading-7 mb-4">
          But most of the time, I would rely on Google Maps, Reddit, Quora,
          Instagram, and other websites to find cool places for dates. After
          making a list of a new found and potential date spots, I would then go
          there to check the vibes myself. Later, I started to pin those liked
          places on my Google Maps or write them down somewhere in my phone.
        </p>

        <p class="font-archivo leading-7 mb-4">
          After creating list of places, I would then write several date ideas
          (with activities, places to go, estimated price, etc.) and put them in
          order. Yes, I'm the person who actually writes down the agenda for the
          date.
        </p>

        <p class="font-archivo leading-7 mb-4">
          Recently I was thinking "Hey, why don't I create a web app that will
          let me to create a list of saved ideas and being able to see them?". I
          looked online for date ideas generators and found forms that gives you
          ideas after setting filters. Most of them didn't have any interface
          and would be just regular questionary form. Few only did have a decent
          interface. BUT all of them had something in common. The ideas were too
          general, and you still had to research those places yourself (let's
          say after completing the form, it tells you to go to a park. Which
          park tho? There are so many? Is there any that has something cool in
          there?). This where GenerDate can be useful for people in Vancouver.
          It's a huge and interesting city with lots of places to check out.
          This app mainly focuses on places around Vancouver (other cities mb
          will be added in the future).
        </p>

        <p class="font-archivo leading-7 mb-4">
          Then, I started to think about my app more thoroughly. Any time me and
          my friends would talk about dates and give each other some tips, I
          would try to keep them in my head or even write them down. In
          GenerDate, you will be able to see articles of selected activities,
          general tips for choosing the right activity with someone, or just
          funny stuff.
        </p>

        <p class="font-archivo leading-7 mb-4">
          I hope you find my app very usefull and it will give you less headache
          from "Where should I take out /name of someone/ on the date?". The
          data shown in here is my own selection of checked places. Please be
          more than welcomed to suggest your places and activities. Your ideas
          may be then added in here.
        </p>

        <p class="font-archivo leading-7 mb-4">- yours truly Raha</p>
      </div>

      <div className="fixed bottom-10 right-10">
        <Image src={gif} alt="gif" width={120} height={120} />
      </div>
    </div>
  );
};

export default About;
