import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "../comps/Hero";
import heroImg from "../public/hero-home.jpg"

export default function Home() {
  return (
    <>
      <Head>
        <title>GenerDate - plan your dates easier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@200;400;500&family=Russo+One&display=swap" rel="stylesheet"/>
      </Head>

      <main class='w-full h-full'>
        <Hero img={heroImg} />
      </main>
    </>
  );
}
