import Head from "next/head";
import { useState } from "react";
import axios from "axios";
import ActivityCard from "../comps/ActivityCard";

export default function Home({ activities }) {
  const [randomActivities, setRandomActivities] = useState([]);

  const handleRandomizeClick = () => {
    const shuffledActivities = [...activities].sort(() => 0.5 - Math.random());
    setRandomActivities(shuffledActivities.slice(0, 5));
  };

  console.log(randomActivities);

  return (
    <>
      <Head>
        <title>Generate Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main className="flex flex-col w-full h-auto text-center justify-center items-center">
        <div class="flex flex-col h-screen bg-white rounded-lg w-11/12 justify-center items-center my-1">
          <h1 className="text-5xl font-bold text-center">
            Random Activities Generator
          </h1>

          <div className="flex flex-col items-center mt-8">
            <button
              className="px-4 py-2 bg-blue-500 text-white rounded-md font-semibold tracking-wide uppercase shadow-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50"
              onClick={handleRandomizeClick}
            >
              Randomize
            </button>

            <div class="flex flex-row flex-wrap overflow-x-auto">
              {randomActivities.length > 0 && (
                <ul className="flex mt-8 space-y-4">
                  {randomActivities.map((activity, index) => (
                    <ActivityCard
                      key={activity.id}
                      link={`activities/${index + 2}`}
                      img={activity.feature}
                      header={activity.name}
                      price={activity.price}
                      city={activity.location}
                      tags={activity.tags}
                    />
                  ))}
                </ul>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps({}) {
  const data = await fetch("https://generdate-api.herokuapp.com/activities");
  const activities = await data.json();

  return {
    props: {
      activities,
    },
  };
}
