import React from "react";
import SavedActivity from "../comps/SavedActivity";
import Head from "next/head";

const Saved = () => {
  return (
    <>
      <Head>
        <title>Saved Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@200;400;500&family=Russo+One&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main class="flex flex-col w-auto overflow-auto items-center justify-center bg-main border-2 border-red-500">
        <div class="w-3/4">
          <h1 class="text-3xl font-roboto-mono font-bold my-4">Saved Ideas</h1>
          <SavedActivity />
        </div>
      </main>
    </>
  );
};

export default Saved;
